// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/279acdc785609096b2f0984aef90b40319c1ac89/striptags/striptags.d.ts
declare module 'striptags' {
    export default function strip (html: string, allowedTags?: string | string[]): string;
}
